name: Upload localization strings to CurseForge

on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v4

      - name: Upload localizations
        uses: p3lim/curseforge-localizations@v1
        with:
          handle_missing: DeletePhrase # optional
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
