name: Notify Discord on Release

on:
  release:
    types: [published]

jobs:
  send-discord-message:
    runs-on: ubuntu-latest
    steps:
      - name: Send release info to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          RELEASE_NAME=$(jq -r .release.tag_name < "$GITHUB_EVENT_PATH")
          RELEASE_URL=$(jq -r .release.html_url < "$GITHUB_EVENT_PATH")
          RELEASE_BODY=$(jq -r .release.body < "$GITHUB_EVENT_PATH")
          
          # Fallback if no description is provided
          [ -z "$RELEASE_BODY" ] && RELEASE_BODY="No description provided."

          # Prepare the payload
          PAYLOAD=$(jq -n \
            --arg content "**New Release: [${RELEASE_NAME}](${RELEASE_URL})**\n\n${RELEASE_BODY}" \
            '{content: $content}')

          # Send the payload to Discord
          curl -X POST -H "Content-Type: application/json" -d "$PAYLOAD" $DISCORD_WEBHOOK_URL
