name: Notify Discord on Release

on:
  release:
    types: [published]

jobs:
  github-releases-to-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Github Releases To Discord
        uses: SethCohen/github-releases-to-discord@v1.13.1
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          color: "16711680"
          username: "XIV_Databar Continued"
          avatar_url: "https://raw.githubusercontent.com/ZelionGG/XIV_Databar-Continued/main/icon.png"
          content: "||@everyone||"
          footer_title: "XIV_Databar Continued Changelog"
          footer_icon_url: "https://raw.githubusercontent.com/ZelionGG/XIV_Databar-Continued/main/icon.png"
          footer_timestamp: true
